# identifiers
# for regular users     => user:name@gmail.com
# for service accounts  => serviceAccount:{{name}}@{{project}}.iam.gserviceaccount.com

default:
    just -l

# creates a service account
service-account-create name description:
    gcloud iam service-accounts create {{name}} \
        --display-name "{{name}}" \
        --description "{{description}}"

# adds role to service account
service-account-role project name role:
    gcloud projects add-iam-policy-binding {{project}} \
        --member "serviceAccount:{{name}}@{{project}}.iam.gserviceaccount.com" \
        --role {{role}}

# roles resource: https://cloud.google.com/iam/docs/understanding-roles#bigquery-roles
# adds required roles for accessing bigquery data and running jobs
service-account-bq-roles project name:
    #!/bin/bash
    roles=(
        "roles/bigquery.jobUser"
        "roles/bigquery.dataOwner"
    )

    for role in "${roles[@]}"; do
        just service-account-role {{project}} {{name}} $role
    done

service-account-roles-print project name:
    gcloud projects get-iam-policy {{project}} --format=json | jq ".bindings[] | select(.members[] | contains(\"{{name}}\")) | .role"

# generates a new service account key file
service-account-key project name output:
    gcloud iam service-accounts keys create {{output}} \
        --iam-account {{name}}@{{project}}.iam.gserviceaccount.com
